server:
  port: 9090

spring:
  application:
    name: ApiGateway

  boot:
    admin:
      client:
        url: http://admin-server:1111
        instance:
          prefer-ip: true

  main:
    web-application-type: reactive

  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000

  cloud:
    gateway:

      httpclient:
        connect-timeout: 10000
        response-timeout: 30s

      # =========================
      # CORS
      # =========================
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://main.d1gezrhyyl9lz2.amplifyapp.com"
             
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      # =========================
      # ROUTES
      # =========================
      routes:

        # Authentication
        - id: auth-service
          uri: lb://AUTHENTICATIONSERVICE
          predicates:
            - Path=/auth/**

        # User
        - id: user-service
          uri: lb://UserService
          predicates:
            - Path=/api/users/**,/api/addresses/**

        # Product
        - id: product-service
          uri: lb://ProductService
          predicates:
            - Path=/api/products/**,/api/categories/**

        # Cart
        - id: cart-service
          uri: lb://CartService
          predicates:
            - Path=/cart/**

        # Order
        - id: order-service
          uri: lb://OrderService
          predicates:
            - Path=/api/orders/**

        # Payment
        - id: payment-service
          uri: lb://PaymentService
          predicates:
            - Path=/api/payments/**


# =========================
# EUREKA
# =========================
eureka:
  client:
    service-url:
      defaultZone: http://serviceregistry:8761/eureka


# =========================
# JWT
# =========================
jwt:
  secret: ${JWT_SECRET:357638792F423F4428472B4B6250655368566D597133397A2443264629}
  expiration: 86400000
